remote_theme: mmistakes/minimal-mistakes@4.15.1
minimal_mistakes_skin: haxor
locale: es-ES
title: jflabur.io
title_separator: '-'
name: Jflabur
description: 'Artículos sobre ciberseguridad, CTFs e investigaciones'
url: 'https://jflabur.github.io'
baseurl: null
repository: jflabur/jflabur.github.io
logo: /assets/images/masthead.png
teaser: null
breadcrumbs: true
words_per_minute: 200
comments:
  provider: false
  disqus:
    shortname: null
  discourse:
    server: null
  facebook:
    appid: null
    num_posts: null
    colorscheme: null
staticman:
  allowedFields: null
  branch: null
  commitMessage: null
  filename: null
  format: null
  moderation: null
  path: null
  requiredFields: null
  transforms:
    email: null
  generatedFields:
    date:
      type: null
      options:
        format: null
reCaptcha:
  siteKey: null
  secret: null
atom_feed:
  path: null
search: null
search_full_content: null
search_provider: null
algolia:
  application_id: null
  index_name: null
  search_only_api_key: null
  powered_by: null
google:
  search_engine_id: null
  instant_search: null
google_site_verification: null
bing_site_verification: null
yandex_site_verification: null
naver_site_verification: null
twitter:
  username: null
facebook:
  username: null
  app_id: null
  publisher: null
og_image: null
social:
  type: null
  name: null
  links: null
analytics:
  provider: google
  google:
    tracking_id: UA-145129883-1
    anonymize_ip: false
author:
  name: Jflabur
  avatar: /assets/images/avatar.png
  bio: Pentester / OSCP / OSWP / eWPTxv2
  location: Barcelona
  email: jflabur@gmail.com
  uri: null
  home: null
  bitbucket: null
  codepen: null
  dribbble: null
  flickr: null
  facebook: null
  foursquare: null
  github: jflabur
  gitlab: null
  google_plus: null
  keybase: null
  instagram: null
  lastfm: null
  linkedin: jflabur
  pinterest: null
  soundcloud: null
  stackoverflow: null
  steam: null
  tumblr: null
  twitter: jflabur
  vine: null
  weibo: null
  xing: null
  youtube: 'https://youtube.com/c/jflabur'
include:
  - .htaccess
  - _pages
exclude:
  - '*.sublime-project'
  - '*.sublime-workspace'
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
keep_files:
  - .git
  - .svn
encoding: utf-8
markdown_ext: 'markdown,mkdown,mkdn,mkd,md'
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: |+


incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: 'lsquo,rsquo,ldquo,rdquo'
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed
permalink: '/:title/'
paginate: 10
paginate_path: '/page:num/'
timezone: null
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
compress_html:
  clippings: all
  ignore:
    envs: development
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: true
